#!/bin/bash

source /opt/sbx/data/sbx.conf
source /opt/sbx/lib/common.sh
source /opt/sbx/lib/system.sh
source /opt/sbx/lib/install.sh
source /opt/sbx/lib/service.sh
source /opt/sbx/lib/runtime.sh
source /opt/sbx/lib/config.sh
source /opt/sbx/lib/route.sh
source /opt/sbx/lib/tools.sh
source /opt/sbx/lib/dashboard.sh
source /opt/sbx/lib/web.sh

root_check


while true
do

dashboard

read -p "请选择：" CHOICE


case "$CHOICE" in

1)

install_menu

;;

2)

config_menu

;;

3)

service_menu

;;

4)

route_menu

;;

5)

tools_menu

;;

6)

web_menu

;;

0)

clear
echo "退出 SBX"
exit 0

;;

*)

warn "输入错误"
pause

;;

esac

done
